// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nucpepnorgppteisbptj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51Y3BlcG5vcmdwcHRlaXNicHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDM4NDIsImV4cCI6MjA1NTYxOTg0Mn0.XUZ-3t7nHlSafiJbgqrooUrQrBLrNGytWTkcl4gDJ1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);